default:
  seed: 0
  wrapper:
    pipeline: [
        "ActionNoise",
        "VirtualClutch",
        "ImageNoise",
        "DepthProcess",
        'Occup',
        "DSA",
        "ObsImage",
        'PID',
        "DiscreteAction",
        "TimeLimit",
        "FSM",
        "ObsVector",
        "GymRegularizer",
      ]
    GymRegularizer: {
      obs_key: ['image','vector','fsm_state'],
    }
    ActionSmooth: { skip: true, window: 3, smooth_type: ema }
    DSA:
      {
        zoom_box_obj: psm1,
        encode_type: occup_depth,
        cv_interpolate: area,
        zoom_box_fix_length_ratio: 0.3,
        zoom_depth_scale: 0.3,
        zoom_depth_offeset: 0.1,
        encoding_id_stuff: 70,
        encoding_id_psm1: 140,
        encoding_id_zoom_box: 30,
        zoom_movement_type: continuous,
        dense_reward: false,
      }
    VirtualClutch: { start: 6 }
    ActionNoise: { noise_scale: 0.01 }
    DiscreteAction: { pos_action_scale: 0.3, rot_action_scale:  1.0, is_discrete: True}
    TimeLimit: { max_timestep: 80 }
    DepthProcess: { skip: false, uncert_scale: 1.5, eval: false , erode_kernel: 0, edge_detect_thres: 0.0, depth_image_range: 0.25}
    FSM: { 
      states: [
              "done_fail",  # done, failure case
              "prog_abnorm_1",  # abnormal 1 : hit workspace limit
              # "prog_abnorm_2",  # abnormal 2 : object sliding
              # "prog_abnorm_3",  # abnormal 3 : gripper toggle
              "prog_norm",  # normal in progress
              "done_success",  # done success case
              ],
      reward_done_success: 1,
      reward_done_fail: -0.1,
      reward_prog_norm: -0.001,
      reward_prog_abnorm_1: -0.01,
      reward_prog_abnorm_2: -0.01,
      reward_prog_abnorm_3: -0.005,
    }
    Occup: {
        skip: false,
        occup_h: 200,
        occup_w: 200,
        occup_d: 200,
        pc_x_min: -0.5,
        pc_x_max: 0.5,
        pc_y_min: -0.5,
        pc_y_max: 0.5,
        pc_z_min: -0.5,
        pc_z_max: 0.5,    
        cam_offset_x: 0.0,
        cam_offset_y: 0.0,
        cam_offset_z: -1.0, 
        cam_offset_rx: 160.0,
        cam_offset_ry: 0.0,
        cam_offset_rz: -90.0,     
        cam_cal_file: './config/cam_cal.yaml',   
        cam_fov: 45,    
        psm_outlier_rm_radius: 0.0,
        psm_outlier_rm_pts: 0,
    }
    PID: {
          obs_type: occup,
          control_p: 10.0,
          phase_thres: [0.1, 0.1, 0.1],
          err_offset: [0.0,  0.0, -0.1],  
          skip: false,
          fsm_z_err_min: -0.06,
    }
    ObsImage: {
      new_image_map_key: "dsa",
      new_image_key: "image",
      new_image_size: 64,
      cv_interpolate: "area",     
    }
    ObsVector: {
      new_vector_map_key: ["gripper_state", "fsm_state", "controller_state"],
      vector2image_type: "row",
    }

    ImageNoise:
      {
        skip: false,
        pns_noise_amount: 0.0,
        pns_noise_balance: 0.0,
        pns_noise_value: 0.0,
        uniform_noise_amount: 0.00,
        gaussian_blur_kernel: 0,
        gaussian_blur_sigma: 0.0,
        cutout_all_amount_range: [1.0, 1.0],
        cutout_depth_amount_range: [1.0, 1.0],
        cutout_line_num_low: 0,
        cutout_line_num_high: 0,
      }
  task_name: grasp_any_v2
  embodied_name: SurrolEnv
  embodied:
    SurrolEnv:
      pybullet_gui: false
      cam_width: 600
      cam_height: 600
      mask_background_id: -3
      depth_remap_range: 0.1
      depth_remap_range_noise: 0
      depth_remap_center_noise: 0
      cam_target_noise: 0.0
      cam_distance_noise: 0.01
      cam_yaw_noise: 0.0
      cam_pitch_noise: 0.0
      cam_roll_noise: 0.0
      cam_up_axis_noise: 0.0
      background_texture_dir: ""
      cam_mode: "rgbdm"
      cam_num: 1
      no_depth_link: false
      mask_except_gripper: false
      disturbance_scale: 0.01
      cam_dynamic_noise_scale: 0.0
      dr_scale_train: 1
      dr_scale_eval: 1
      grasp_any_v2:
        stuff_name: needle
        fix_goal: true
        noise_scale: 1.0
        done_z_thres: 0.2
        init_pose_ratio_low_gripper: [-0.9, -0.9, 0.5, -0.9]
        init_pose_ratio_high_gripper: [-0.9, 0.9, 0.9, 0.9]
        init_pose_ratio_low_stuff: [-0.8, -0.8, 0.1, -0.99,-0.99,-0.99]
        init_pose_ratio_high_stuff: [0.8, 0.8, 0.5, 0.99, 0.99, 0.99]
        random_obj_vis: false
        depth_distance: 0.2
        on_plane: false
        oracle_pos_thres: 25e-4
        oracle_rot_thres: 0.5
        max_grasp_trial: 1
        horizontal_stuff: true
        object_scaling_low: 0.75
        object_scaling_high: 1.25
        object_list: ['needle', "box", "bar"]
        needle_prob: 0.5
    dVRKEnv:
      robot_type: 'dvrk'
      grasp_any_v2:
        arm_names: ["PSM1"]
        rgbd_device: "stereo"
        ws_x: [-0.1, 0.1]
        ws_y: [-0.1, 0.1]
        ws_z: [-0.24, 0.0]
        psm_reset_q: [0.0, 0.0, 0.12, 0.0, 0.0, 0.0]
        psm_open_gripper_deg: 40.0
        psm_init_gripper_quat: [7.07106781e-01, 7.07106781e-01, 0.0, 0.0]
        psm_init_pose_low_gripper: [0.0, 0.0, 0.0, 0.0]
        psm_init_pose_high_gripper: [0.0, 0.0, 0.0, 0.0]
        psm_max_step_pos: 0.01
        psm_max_step_rot: 45.0
        cam_image_height: 600
        cam_image_width: 600
        cam_depth_remap_center: 0.3
        cam_depth_remap_range: 0.1
        dvrk_cal_file: "./data/dvrk_cal/dvrk_cal.yaml"
        cam_segment_tool: "track_any"
        cam_segment_model_dir: "./data/dvrk_cal/color_seg_cal.yaml"
        cam_cal_file: ""
        done_cal_file: ""
        cam_mask_noisy_link: true
        done_device: "keyboard"
        reset_random_pose: false



gasv2_dvrk:
  task_name: grasp_any_v2
  embodied_name: dVRKEnv
  wrapper.PID: {
          control_p: 15.0,
          phase_thres: [0.015, 0.015, 0.015],
          err_offset: [0.0,  0.0, -0.005],  
    }
  wrapper.DiscreteAction.pos_action_scale: 0.2
  wrapper.ImageNoise.skip: true
  wrapper.ActionNoise.noise_scale: 0.0
  wrapper.DepthProcess.eval: true
  wrapper.Occup: {
        pc_x_min: -0.1,
        pc_x_max: 0.1,
        pc_y_min: -0.1,
        pc_y_max: 0.1,
        pc_z_min: -0.1,
        pc_z_max: 0.1,    
        cam_offset_z: -0.13548762, 
        cam_offset_rx: 160,
        cam_offset_ry: 0.0,
        cam_offset_rz: -90.0,     
        cam_cal_file: './config/cam_cal.yaml',   
        psm_outlier_rm_radius: 0.001,
        psm_outlier_rm_pts: 30,
  }




################################################
## other setting that might not work

dsa_occup2:
  wrapper.DSA.encode_type: occup_depth2

domain_random_enhance:
  wrapper.ImageNoise: {
    cutout_all_amount_range: [0.8, 1.0],
    pns_noise_amount: 0,
    pns_noise_balance: 0.5,
    pns_noise_value: 1,
    uniform_noise_amount: 0.005,
    gaussian_blur_kernel: 3,
    gaussian_blur_sigma: 0.3,
  }
  embodied.SurrolEnv: {
    pybullet_gui: false,
    cam_target_noise: 0.0,
    cam_distance_noise: 0.05,
    # cam_yaw_noise: 5
    cam_pitch_noise: 3,
    cam_roll_noise: 3,
    cam_up_axis_noise: 1
    }
######################################
# evaluation settings

# generality
object_scale1:
  embodied.SurrolEnv.grasp_any_v2:
      {
        object_scaling_low: 1.5,
        object_scaling_high: 2.0,
        object_list: ['needle', "box", "bar"],
        needle_prob: 0.5,
      }
object_scale2:
  embodied.SurrolEnv.grasp_any_v2:
      {
        object_scaling_low: 1.5,
        object_scaling_high: 2.0,
        object_list: ['needle', "box", "bar"],
        needle_prob: 0.5,
      }
object_type1:
  embodied.SurrolEnv.grasp_any_v2:
      {
        # object_scaling_low: 1.5,
        # object_scaling_high: 2.0,
        object_list: ["sphere"],
        # needle_prob: 0.5,
      }

# robust
regrasp:
  embodied.SurrolEnv.grasp_any_v2.max_grasp_trial: 2
dynamic_cam:
  embodied.SurrolEnv.cam_dynamic_noise_scale: 0.1


  
########################
# other
psm2:
  embodied.dVRKEnv.grasp_any_v2.arm_names: ["PSM2"]


gui: 
  embodied.SurrolEnv.pybullet_gui: true

timelimit_debug:
  wrapper.TimeLimit: { max_timestep: 1}

no_depth_process:
  wrapper.DepthProcess.skip: True

no_pid:
  wrapper.PID.skip: true

no_clutch:
  wrapper.VirtualClutch.start: 0

action_continuous:
  wrapper.DiscreteAction.is_discrete: False  


gasv1:
  wrapper.Occup.skip: false 
  wrapper.PID.skip: true
  wrapper.DSA: {
        encode_type: general_simple3,
        encoding_id_stuff: 60,
        encoding_id_psm1: 130,
        encoding_id_zoom_box: 30,
        }
  wrapper.ObsVector.vector2image_type: "square"

raw_env:
  wrapper.Occup.skip: false 
  wrapper.PID.skip: true
  wrapper.DSA: {
        encode_type: raw,
        }
  wrapper.VirtualClutch.start: 0

no_dsa:
  wrapper.DSA: {
        encode_type: raw,
        }

all_obs:
  wrapper.GymRegularizer.obs_key: ["all"]



