camera0: 2
camera1: 0
frame_width: 800
frame_height: 600
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 5
checkerboard_rows: 11
checkerboard_columns: 8
cooldown: 100
